Repository c0sm0void/ReVot, pull requests merged in 2024-10, with the labels that each got.

#16 Add CONTRIBUTING.md to Guide New Contributors
  CONTRIBUTING.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#15 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#11 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#28 Additon of All Contributors | Issue #24
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#35 docs: enhance documentation for ReVot
  .github/workflows/update-readme.yml
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#37 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#40 Makeitalive fix
  reverse_image_search_bot/commands.py
Labels: bug, hacktoberfest-accepted, hacktoberfest

#27 Add Contributor Section
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#44 Fixes #43: Updated README.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#42 Implement Auto Labeler GitHub Action for Issues and Pull RequestsLabel
  .github/workflows/labeler.yml
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#47 Added .gitignore
  .gitignore
Labels: hacktoberfest-accepted, hacktoberfest

#50 want to add more stats and animation to README to make it attractive #46
  Pipfile
  README.md
  pre-installations
  pre-installations.sh
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#51 Auto labeler workflow failing #48
  .github/workflows/labeler.yml
Labels: bug, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#56 Added rate limit.
  reverse_image_search_bot/bot.py
  reverse_image_search_bot/commands.py
  reverse_image_search_bot/image_search.py
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level2

#54 Added automated greetings bot
  .github/workflows/greetings.yml
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#76 Update labeler.yml
  .github/workflows/labeler.yml
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level?

#79 Added Table of Contents in Readme file
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#70 Update commands.py
  reverse_image_search_bot/commands.py
Labels: bug, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level3

#86 CI/CD workflow
  .github/workflows/ci-cd.yml
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1, workflow

#87 Add feature: Platform Detection
  pre-installations.sh
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#89 fix issue #69
  README.md
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level?

#92 GitHub action PR Issue checker
  .github/workflows/PRValidator.yml
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level2

#96 Github actions for more connectivity!
  .github/workflows/greetings.yml
  .github/workflows/issue_open_close.yml
  .github/workflows/pr_merge.yaml
  .github/workflows/pr_raise.yml
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level2, workflow

#101 Documentation: UPDATE Of Contributing.md #100
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#103 Update README.md #102
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level0

#106 Updated README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#108 Added Table in Readme to display statistics
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1
